dataset_bg_dir: "/root/autodl-tmp/yolo/dataset/backgrounds"

model:
  vision_model_name: "vit_large_patch14_dinov2.lvd142m"
  text_encoder: "roberta-large"
  resolution: 756
  film_layers: [6, 12, 18, 23]
  film_hidden_dim: null
  feature_aggregation: "mean"
  modulate_prefix_tokens: false
  pretrained_vision: true

optim:
  lr: 0.0001
  weight_decay: 0.0001

trainer:
  batch_size: 2
  num_epochs: 10
  random_pad: true
  val_split: 0.1

local_inferer:
  name: "earlyfilm"
  checkpoint_path: null
  load_strict: false
  model:
    vision_model_name: "vit_large_patch14_dinov2.lvd142m"
    text_encoder: "roberta-large"
    resolution: 756
    film_layers: [6, 12, 18, 23]
    film_hidden_dim: null
    feature_aggregation: "mean"
    modulate_prefix_tokens: false
    pretrained_vision: true
