dataset_bg_dir: None

model:
  in_channels: 1024
  filters: [256, 64, 1]
  kernel_sizes: [3, 3, 1]
  strides: [1, 1, 1]
  norm: null
  activation: "lrelu"
  lang_emb_dim: 1024
  film_mode: "rand"

text_embedding: "embeddings_oai"

optim:
  lr: 0.002
  weight_decay: 0.0
  step_size: 10
  gamma: 0.75

trainer:
  batch_size: 32
  num_epochs: 50
  save_every: 10
  val_every: 10
  random_pad: true
  val_split: 0.1

criterion: "BCE"
torch_home: None

dino_model_type: "dinov2_vitl14"
dino_use_registers: False
torch_home: None